HW-02_all_done
js-tasks-ru/jsbasic-20210921-5_piatnytskiy-y-m pull request #4
Opened 2021-10-13 09:18 UTC by Hilarey

HW - 02 - Все 3 задачи сделаны.

2021-10-13 09:19 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2021-10-17 06:36 UTC, koalex requested changes

2021-10-17 06:36 UTC, koalex commented on 2-module/3-task/index.js
> +    this.a = +("a:", a);
`+("a:", a);` зачем это? Нужно так: `this.a = a`

2021-10-17 09:24 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2021-10-17 09:27 UTC, Hilarey commented on 2-module/3-task/index.js
> +    this.a = +("a:", a);
read(a, b) (читать) запрашивает два значения и сохраняет их как свойства объекта.
Я прочитал это и сделал так, что оно запрашивает через промпт два значения 
  read(a, b) { this.a = +prompt('a:', a), this.b = +prompt('b:', b) },

2021-10-17 14:34 UTC, koalex approved these changes

2021-10-17 14:34 UTC, merged